fix(wsl): spotify support
JanDeDobbeleer/oh-my-posh pull request #1028
Opened 2021-10-08 01:17 UTC by bewing

### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes/features)

### Description

Support Spotify segment inside WSL

2021-10-08 10:22 UTC, JanDeDobbeleer commented on src/segment_git_test.go
> +	env.On("isWsl", nil).Return(false)
why is this added?

2021-10-08 10:24 UTC, JanDeDobbeleer commented on src/segment_spotify_others.go
> +	tlist, err := s.env.runCommand("tasklist.exe", "/V", "/FI", "Imagename eq Spotify.exe", "/FO", "CSV", "/NH")
This will only work on WSL, can we rename the file to `segment_spotify_wsl.go`?

2021-10-08 10:25 UTC, JanDeDobbeleer commented on src/segment_spotify_others.go
> +		title := record[len(record)-1]
what if `len(record) == 0`?

2021-10-08 10:27 UTC, JanDeDobbeleer commented on src/segment_spotify_others_test.go
> +func bootStrapSpotifyOtherTest(args *spotifyArgs) *spotify {
Can you use the new style we have like in [this](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/segment_ruby_test.go#L10) test for example?

2021-10-08 10:28 UTC, JanDeDobbeleer requested changes
A few remarks/questions. Would be good to rename the file(s).

2021-10-09 16:41 UTC, bewing commented on src/segment_git_test.go
> +	env.On("isWsl", nil).Return(false)
This is added as it would panic without it due to the change at https://github.com/JanDeDobbeleer/oh-my-posh/pull/1028/files#diff-937c113f57efe859eff30ab6e3674e71a981563d47c10f826aeefe8e2e0f7c1bR149

2021-10-09 16:42 UTC, bewing commented on src/segment_spotify_others.go
> +		title := record[len(record)-1]
Covered in test at https://github.com/JanDeDobbeleer/oh-my-posh/pull/1028/files#diff-4e9c0a52809c48bdd0100d81eb90ccbec75b3f047fbef841b265e0bb4cc93e73R19

2021-10-09 16:42 UTC, bewing commented on src/segment_spotify_others_test.go
> +func bootStrapSpotifyOtherTest(args *spotifyArgs) *spotify {
Will refactor this weekend

2021-10-09 16:44 UTC, bewing commented on src/segment_spotify_others.go
> +	tlist, err := s.env.runCommand("tasklist.exe", "/V", "/FI", "Imagename eq Spotify.exe", "/FO", "CSV", "/NH")
renamed

2021-10-10 21:23 UTC, bewing commented on src/segment_spotify_others_test.go
> +func bootStrapSpotifyOtherTest(args *spotifyArgs) *spotify {
Refactored in latest commit.

2021-10-11 06:48 UTC, JanDeDobbeleer commented
@bewing the commit can't start with an upper case. So you'll have to rename to `fix(wsl): spotify support`

2021-10-11 07:02 UTC, merged

2021-10-11 07:04 UTC, JanDeDobbeleer commented
@all-contributors please add @bewing for code