fix(path): correctly handle replaced paths for letter style
JanDeDobbeleer/oh-my-posh pull request #1050
Opened 2021-10-16 06:47 UTC by aexvir

### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes/features)

### Description

Currently, when using the `letter` style on the `path` segment, together with `mapped_locations` that replace directories with icons, the icon gets malformed as the mapped locations are applied before the segment style is applied, and the segment code naively gets the first character of the folder for every level.

This also affects directories that have characters on the extended unicode range, like `äcker`, as getting the first character from that string doesn't pick up the whole letter `ä`.

example:
<img width="760" alt="Screenshot 2021-10-16 at 08 32 35" src="https://user-images.githubusercontent.com/8055505/137576603-a3fc9880-c1e2-4f6d-ac5f-3d25ddbab413.png">

This merge request addresses this problem by extracting from the folder name the first letter, taking in account the unicode extended range, and not doing any replacement in case there is no letter on the folder at all, which would happen when the icon gets replaced by the mapped locations processor, or if the folder name would be exclusively formed by non-letters nor numbers, which I think it's unlikely to happen

so now it looks like:
<img width="760" alt="Screenshot 2021-10-16 at 08 46 57" src="https://user-images.githubusercontent.com/8055505/137576964-68e59c60-66cf-4c32-a6de-613ee7c061f1.png">

---

note:
currently, directories like python's `__pycache__` are get shortened to just `_`; as I wanted to handle the case where the replacement would include an icon and some text, e.g. `➼ something`, I've changed this logic, and shorten to until the first letter that was found instead
* for `__pycache__` it would get shortened to `__p`
* for `➼ something` it would get shortened to `➼ s`

2021-10-16 14:20 UTC, JanDeDobbeleer approved these changes

2021-10-16 14:21 UTC, JanDeDobbeleer commented
@aexvir how did you create those screenshots?

2021-10-16 14:26 UTC, JanDeDobbeleer requested changes
@aexvir only the CI reported issues need to be addressed and we're good to go!

2021-10-17 07:16 UTC, aexvir commented
> @aexvir how did you create those screenshots?

it's just [iterm2](https://gitlab.com/gnachman/iterm2) on macOS; made the font bigger so the prompt could be easily visible, then I did a [window screenshot](https://support.apple.com/en-us/HT201361#:~:text=How%20to%20capture%20a%20window%20or%20menu)

> @aexvir only the CI reported issues need to be addressed and we're good to go!

should be fixed now 🙂

2021-10-17 11:03 UTC, JanDeDobbeleer commented
> then I did a [window screenshot](https://support.apple.com/en-us/HT201361#:~:text=How%20to%20capture%20a%20window%20or%20menu)

I had no idea that was possible, thanks!

2021-10-17 11:06 UTC, merged