feat: support color names for basic 16 ANSI colors
JanDeDobbeleer/oh-my-posh pull request #129
Opened 2020-11-06 17:35 UTC by samuelfahrngruber

Closes #127

### Prerequisites

- [x] I have read and understand the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### Description

Adds support to also use basic color names such as `green` or `lightBlue` for the basic 16 ANSI color escape codes. From now on such names can be specified in addition to hex color codes. I added some more details to the issue #127.

I am not very familiar with go (tbh, not at all, I got to know it a bit on the fly), so I'd love to get some feedback on improving the code. In general I'd appreaciate any kind of feedback and suggestions here 😄 

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

2020-11-06 17:49 UTC, JanDeDobbeleer commented
@samuelfahrngruber: `body's lines must not be longer than 100 characters [body-max-line-length]` ;-)

2020-11-08 16:05 UTC, JanDeDobbeleer requested changes
Final comments ;-) After that we're ready to merge.

2020-11-08 16:05 UTC, JanDeDobbeleer commented on renderer.go
> +	if isBackground && err == nil {
These checks can be simplified to:

```golang
if err == nil {
  style := color.HEX(colorString, isBackground)
  return style.Code()
}
return colorFromName
```

2020-11-08 16:05 UTC, JanDeDobbeleer commented on renderer.go
> +func getColorFromName(colorName string) (string, string, error) {
I would extend this with `, isBackground bool` just like `color.HEX` and return `(string, error)`. That way we can simplify the function below.

2020-11-08 17:53 UTC, samuelfahrngruber commented on renderer.go
> +	ColorMap map[string][2]string = map[string][2]string {
Went for a map in order to still have one key identifying a background-foreground color pair and not get too complex `if`s and `switch`es. What do you think? 🤔

2020-11-08 19:24 UTC, merged