Added theme "Smoothie"
JanDeDobbeleer/oh-my-posh pull request #1461
Opened 2021-12-17 23:47 UTC by PapiPeppers

### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes/features)

### Description

Added new theme named "smoothie" to /themes. Preview images in forked repo's README.

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

2021-12-18 19:20 UTC, JanDeDobbeleer requested changes
You need to remove the images and the addition to the README. Other than that, just 1 remark 👍🏻

2021-12-18 19:20 UTC, JanDeDobbeleer commented on README.md
> +# Forked Repo Changes
this will also appear in this repo so it needs to be removed

2021-12-18 19:20 UTC, JanDeDobbeleer commented on themes/smoothie.omp.json
> +			"postfix": " ",
default value, can be removed

2021-12-18 21:26 UTC, PapiPeppers commented
all should be good to go now. thanks!

2021-12-19 08:32 UTC, merged

2021-12-19 08:35 UTC, JanDeDobbeleer commented
@all-contributors please add @PapiPeppers for design