feat(folder-depth): Extends Folder to use max_depth
JanDeDobbeleer/oh-my-posh pull request #1846
Opened 2022-03-01 06:09 UTC by jedwillick

### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes/features)

### Description

Extends the Folder path style to display the names of the last `max_depth` folders, separated by the `folder_separator_icon`. 

With a `max_depth` of 2:
![image](https://user-images.githubusercontent.com/85419773/156113600-8775e115-7f63-4d07-8cb1-7d4fac7fe671.png)

Having the default `max_depth` of 1, works the same way as before, displaying only the current folder.
![image](https://user-images.githubusercontent.com/85419773/156113675-2066ed36-87fb-4954-aaca-2ab1d07c8e97.png)

Kind Regards,
Jed

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

2022-03-01 06:50 UTC, JanDeDobbeleer requested changes

2022-03-01 06:50 UTC, JanDeDobbeleer commented on src/segments/path.go
> +	pathSeparator := pt.env.PathSeparator()
this and the above code is almost identical, can we find a way to reuse it?

2022-03-01 08:12 UTC, jedwillick commented
I fixed the repeated logic but now im kinda thinking that maybe there should just be an option in agnoster_short to remove always showing the root folder. What are your thoughts?

2022-03-01 08:56 UTC, JanDeDobbeleer commented
@jedwillick I would try it 😃

2022-03-01 10:20 UTC, jedwillick commented
Updated PR. Added an `hide_root` option to `agnoster_short` instead of chagning `folder`.

2022-03-01 12:21 UTC, JanDeDobbeleer requested changes

2022-03-01 12:21 UTC, JanDeDobbeleer commented on docs/docs/segment-path.md
> +- hide_root: `boolen` -  hides the root directory if it doesn't fit in the last `max_depth` folders, when using
- typo: `boolean`
- needs to be `agnoster_short`

2022-03-01 12:21 UTC, JanDeDobbeleer commented on src/segments/path.go
> +	HideRoot properties.Property = "hide_root"
I would rename to `hide_root_location` as it can be ambiguous.

2022-03-01 12:21 UTC, JanDeDobbeleer commented on src/segments/path.go
> +		pathDepth--
this needs a comment as it's a bit magic once the context of this PR is gone.

2022-03-02 22:57 UTC, jedwillick commented
Made requested changes.

- [x] Fixed typo (`boolen` -> `boolean`)
- [x] Changed `Agnoster Short` -> `agnoster_short`
- [x] Changed `hide_root` -> `hide_root_location`
- [x] Added comment to the magic part and flipped logic to hopefully make it more clear aswell
- [x] Also added a few more tests

2022-03-03 06:59 UTC, JanDeDobbeleer commented
@jedwillick on a roll :-) Awesome tbh.

2022-03-05 12:12 UTC, merged