feat: package segment
JanDeDobbeleer/oh-my-posh pull request #1901
Opened 2022-03-11 14:30 UTC by estruyf

### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes/features)

### Description

New package segment to show the version of the package file. Created in a generic way so that other types can be added in the future.

![image](https://user-images.githubusercontent.com/2900833/157886933-fabf45d2-a775-4ae0-8ee0-c4aa8ca5c0f6.png)

2022-03-11 15:35 UTC, JanDeDobbeleer requested changes
I love the extensibility, but wonder if the name is correct in that case. In the end what it does is provide the version number of the project, right?

2022-03-11 15:35 UTC, JanDeDobbeleer commented on src/segments/package.go
> +	packages []PackageItem
you can make this a pointer array so you always pass by reference:

```go
packages []*PackageItem
```

2022-03-11 15:35 UTC, JanDeDobbeleer commented on themes/schema.json
> +            "title": "NPM Segment",
Wrong title :-)

2022-03-11 16:18 UTC, estruyf commented on src/segments/package.go
> +	packages []PackageItem
Need to get more familiar with Go it seems. 🤓

2022-03-11 16:21 UTC, JanDeDobbeleer commented on src/segments/package.go
> +	packages []PackageItem
That's why I'm here :-)

2022-03-11 16:24 UTC, estruyf commented on src/segments/package.go
> +	packages []PackageItem
Should have known, as, in the test, I got a warning to use the pointer notation `*` because the object reference was otherwise too big.

2022-03-11 17:43 UTC, estruyf commented
Yes, got the inspiration from Starship, there it's also called "package", but it can be anything else. 

On some cases, the project is the actual package version, but still,  it's a project. Shall we go for "project", leave it, or do you have another suggestion?

2022-03-11 17:55 UTC, JanDeDobbeleer commented
Project makes sense 👍🏻

2022-03-12 19:48 UTC, estruyf commented
Updated the files and code to use `project` instead.

2022-03-12 21:05 UTC, JanDeDobbeleer approved these changes

2022-03-12 21:08 UTC, merged