feat(python) Support pyenv .python-version files
JanDeDobbeleer/oh-my-posh pull request #2063
Opened 2022-04-09 19:11 UTC by bewing

Pyenv will use .python-version files up the file heirarchy when
determining the active Python version or virtual environment to use
based on which folder your shell is in.  This change will read the file,
and if the first line does not look like a Python version, set the Venv
to that string for display.

### Prerequisites

- [x] I have read and understood the `CONTRIBUTING` guide
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes/features)

### Description
Read .python-version files to determine virtualenv if environment variable search turns up empty.
Note:  Does not read $PYENV_ROOT/version -- should we?
Question:  Would it be better to just parse `pyenv version-name` in PWD to get `version[:venv name]` ?

[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

2022-04-15 18:44 UTC, JanDeDobbeleer commented
@bewing I can do the changes if you don't have time, would love to merge this one.

2022-04-19 13:06 UTC, bewing commented
> @bewing I can do the changes if you don't have time, would love to merge this one.

I think this change is useful enough on its own -- I will add a config gate and documentation today.

2022-04-19 19:22 UTC, JanDeDobbeleer requested changes

2022-04-19 19:22 UTC, JanDeDobbeleer commented on src/segments/python.go
> +		re := regexp.MustCompile("[0-9]+.[0-9]+.[0-9]+") // Don't display version twice
Have a look at our regex functionality, it caches everything for you.

2022-04-19 19:23 UTC, JanDeDobbeleer commented on src/segments/python.go
> +		re := regexp.MustCompile("[0-9]+.[0-9]+.[0-9]+") // Don't display version twice
@bewing I had this pending request I did not submit 🤦🏻

2022-04-19 20:45 UTC, JanDeDobbeleer approved these changes

2022-04-19 20:45 UTC, merged