feat(project): enhance project segment with .NET
JanDeDobbeleer/oh-my-posh pull request #3019
Opened 2022-10-26 12:25 UTC by lesfiddler

### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)

### Description

Enhance `project.go` by fetching current .NET project version.

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

2022-10-26 14:29 UTC, JanDeDobbeleer requested changes

2022-10-26 14:29 UTC, JanDeDobbeleer commented on src/segments/project.go
> +	tag := "(?P<tag><.*TargetFramework.*>(?P<tfm>.*)</.*TargetFramework.*>)"
Can we make `tag` and `tfm` uppercase? Let's not forget to also change below in that case.
```suggestion
	tag := "(?P<TAG><.*TargetFramework.*>(?P<TFM>.*)</.*TargetFramework.*>)"
```

2022-10-26 15:41 UTC, babieiev commented
@JanDeDobbeleer it's strange that the `ubuntu` test fails because the lines are repeated three times. I didn't know that in `golang` everything is so strict with this 😅. Should I create local constants or do something else?

2022-10-26 15:51 UTC, JanDeDobbeleer commented
@lesfiddler I'll check. One question I also have is that the behavior of this check still different compared to the others in project as they parse the project version number and not a target framework. Maybe we can extend the segment to have both values as both go and node definitely offer that. I bet there's also a `Version` property in the `Solution` file.

2022-10-26 16:14 UTC, lesfiddler commented
> I bet there's also a `Version` property in the `Solution` file.

@JanDeDobbeleer unfortunately, I do not think that it is possible. Regarding the `.sln` file, @PilotBob already wrote in issue #1568:

> There is no distinction in a .sln file unfortunately.

Also, there is no information about this in the [official documentation](https://learn.microsoft.com/en-us/visualstudio/extensibility/internals/solution-dot-sln-file). Moreover, modern `dotnet` allows you to have projects without a `.sln` file. It is mostly needed to maintain the hierarchy of projects. The only version it contains is the Visual Studio version.

2022-10-26 16:53 UTC, lesfiddler commented
> One question I also have is that the behavior of this check still different compared to the others in project as they parse the project version number and not a target framework.

I know that the behavior is not similar to any segment (that's why I suggested making a separate segment in [my previous PR](https://github.com/JanDeDobbeleer/oh-my-posh/pull/3005)). However, the project, in comparison with others, is the most suitable for this

2022-10-27 05:46 UTC, JanDeDobbeleer commented
@lesfiddler alright, so I had a good thought on this and we'll need an additional Property called `.Target` here where we add this version number. I can extend the other languages like Node and go who have this as well.

2022-10-27 07:31 UTC, lesfiddler commented
@JanDeDobbeleer if I understood it correctly, I should add a new property, but.. where exactly? `project.go` or `language.go`?

2022-10-27 07:49 UTC, JanDeDobbeleer commented
@lesfiddler I'll do it. Don't worry, the PR is perfect, I can take over.

2022-10-27 10:32 UTC, JanDeDobbeleer commented
@lesfiddler 👀

2022-10-27 10:49 UTC, lesfiddler commented
@JanDeDobbeleer looks good. Do I need to do something?

2022-10-27 11:55 UTC, JanDeDobbeleer commented
@lesfiddler nope, merging right away!

2022-10-27 11:55 UTC, merged