feat: add max_cols option in segment
JanDeDobbeleer/oh-my-posh pull request #3150
Opened 2022-12-01 16:27 UTC by mirsella

If the terminal width exceeds this value, the segment will be hidden.
Need testing on Windows.

Follow up of discussion https://github.com/JanDeDobbeleer/oh-my-posh/discussions/3148

I hope the doc changes are good.
thanks !

2022-12-01 16:34 UTC, mirsella commented
![image](https://user-images.githubusercontent.com/45905567/205107818-db8a0994-b553-4cab-8289-fb9677fbbfb0.png)

i still need to figure out why the RPROMPT is on the newline, i want it on the first line with the PROMPT. if you have a guess i'm taking. thanks

2022-12-01 16:47 UTC, JanDeDobbeleer commented
@mirsella rprompt will ALWAYS be on the same line as the cursor. That's by design.

2022-12-01 16:48 UTC, mirsella commented
oh ok, thanks for clearing things up

2022-12-01 19:43 UTC, JanDeDobbeleer requested changes

2022-12-01 19:43 UTC, JanDeDobbeleer commented on src/engine/segment.go
> +	if width, _, err := term.GetSize(int(os.Stdin.Fd())); err == nil && segment.MaxCols > 0 && width > segment.MaxCols {
```suggestion
	if width, err := segment.env.TerminalWidth(); err == nil && segment.MaxCols > 0 && width > segment.MaxCols {
```
We actually have this number already for other means so no use for a specific library here. Make sure to use `go mod tidy` after applying this change to remove the dependencies.

2022-12-01 19:43 UTC, JanDeDobbeleer commented on website/docs/configuration/segment.mdx
> +| `max_cols`             | `int`        | if the terminal width exceeds this value, the segment will be hidden. for your terminal width, see `tput cols`. Defaults to `0`
`tput cols` is a unix functionality, I would replace that by adding a `oh-my-posh get cols` [command](https://github.com/JanDeDobbeleer/oh-my-posh/blob/d34d9d368c1b74b12734dfb552ab711ab7d0ade1/src/cli/get.go#L46).

2022-12-01 19:45 UTC, JanDeDobbeleer commented
General question, do we want to add a `min_cols` setting as well? if so it can all become very responsive.

2022-12-01 19:51 UTC, mirsella commented
I'll look into it tomorrow when I get back to my pc.
we can add a min_cols while we are at it

2022-12-01 19:55 UTC, JanDeDobbeleer commented
@mirsella we've got time. I'm not in a hurry.

2022-12-02 10:07 UTC, mirsella commented
Tell me if there is anything else !

2022-12-02 21:08 UTC, mirsella commented
Accidentally merged your main branch with this PR but the commit message wasn't conventional, so i deleted it

2022-12-03 10:18 UTC, JanDeDobbeleer approved these changes

2022-12-03 10:20 UTC, merged

2022-12-03 10:20 UTC, JanDeDobbeleer commented
@all-contributors please add @mirsella for code,design,doc