feat: add mercurial segment
JanDeDobbeleer/oh-my-posh pull request #3340
Opened 2023-01-10 01:37 UTC by davidcourtney

### Prerequisites

- [X] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [X] The commit message follows the [conventional commits][cc] guidelines
- [X] Tests for the changes have been added (for bug fixes/features)
- [X] Docs have been added/updated (for bug fixes/features)

### Description

Added a segment for the [Mercurial][mercurial] source control system

[mercurial]: https://www.mercurial-scm.org
[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

2023-01-10 07:47 UTC, JanDeDobbeleer requested changes

2023-01-10 07:47 UTC, JanDeDobbeleer commented on src/segments/mercurial.go
> +		hg.Working = &MercurialStatus{}
you could initialise this above and drop the initialisation at line 97. In that case you don't need and `if else`.

2023-01-10 07:47 UTC, JanDeDobbeleer commented on src/segments/mercurial.go
> +	if idString == "" {
```suggestion
	if len(idString) == 0 {
```

for consistency with everything else

2023-01-10 07:47 UTC, JanDeDobbeleer commented on src/segments/mercurial.go
> +	hg.ChangeSetIDShort = idSplit[1][:12]
this length isn't validated, should we do that?

2023-01-10 07:47 UTC, JanDeDobbeleer commented on src/segments/mercurial.go
> +	if statusString == "" {
```suggestion
	if len(statusString) == 0 {
```

2023-01-10 07:47 UTC, JanDeDobbeleer commented on src/segments/mercurial.go
> +	if s == "" {
```suggestion
	if len(s) == 0 {
```

2023-01-11 01:08 UTC, davidcourtney commented
I made all the suggested changes and rebased the branch commit from the latest in main.

2023-01-11 14:18 UTC, JanDeDobbeleer approved these changes

2023-01-11 14:25 UTC, merged

2023-01-11 14:25 UTC, JanDeDobbeleer commented
@all-contributors please add @davidcourtney for code,design,doc