Unity segment improvements
JanDeDobbeleer/oh-my-posh pull request #3547
Opened 2023-03-02 13:54 UTC by cabauman

### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md]
- [x] The commit message follows the [conventional commits][cc] guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)

### Description

Resolves #3538

2023-03-03 13:21 UTC, JanDeDobbeleer requested changes

2023-03-03 13:21 UTC, JanDeDobbeleer commented on src/segments/unity.go
> +var csharpVersionsByUnityVersion = map[string]string{
can we add this in `GetCSharpVersion()`? That way the map isn't loaded into memory if you're not using the segment.

2023-03-03 13:21 UTC, JanDeDobbeleer commented on src/segments/unity.go
> +	u.env.Debug(fmt.Sprintf("Unity version %s doesn't exist in the map. Now making web request...", shortUnityVersion))
```suggestion
	u.env.Debug(fmt.Sprintf("Unity version %s doesn't exist in the map", shortUnityVersion))
```

2023-03-04 07:16 UTC, JanDeDobbeleer approved these changes

2023-03-04 07:29 UTC, merged

2023-03-04 07:30 UTC, JanDeDobbeleer commented
@all-contributors please add @cabauman for code,doc

2023-03-04 07:33 UTC, cabauman commented
Thank you so much for your time and guidance through this whole process. I love what you've done with this repository.