Accessibility updates
JanDeDobbeleer/oh-my-posh pull request #4402
Opened 2023-10-30 01:45 UTC by mishmanners

### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md].
- [x] The commit message follows the [conventional commits][cc] guidelines.
- [ ] Tests for the changes have been added (for bug fixes / features).
- [ ] Docs have been added/updated (for bug fixes / features).

### Description

Add accessibility features based on: https://github.blog/2023-10-26-5-tips-for-making-your-github-profile-page-accessible/

Having links next to the text is ideal for accessibility. You have some double links though so I couldn't change those.

### How

NA

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

2023-10-30 07:23 UTC, JanDeDobbeleer requested changes

2023-10-30 07:23 UTC, JanDeDobbeleer commented on README.md
> +![Documentation link badgeL ohmyposh.dev][docs-badge]][docs]
```suggestion
![Documentation link badge ohmyposh.dev][docs-badge]][docs]
```

small typo I believe

2023-10-30 07:24 UTC, JanDeDobbeleer commented
You'll also need to adjust the commit message to respect the conventional commit guidelines, or, I squash the changes and change the message myself.

2023-10-30 07:30 UTC, mishmanners commented
Hmmm, how do I change a commit message?

2023-10-30 07:48 UTC, JanDeDobbeleer commented
> Hmmm, how do I change a commit message?

From the web UI I don't know (assuming that's how you did this due to seeing the `patch-1` branch name). I have a guide on that using the CLI and GitKraken [here](https://ohmyposh.dev/docs/contributing/git#i-didnt-stick-to-the-conventional-commit-guidelines).

2023-10-30 22:46 UTC, mishmanners commented
okay that should be good now @JanDeDobbeleer. Let me know if it's all good to go.

2023-11-01 07:36 UTC, JanDeDobbeleer commented
> okay that should be good now @JanDeDobbeleer. Let me know if it's all good to go.

@mishmanners you added a third commit, but the initial two still remained. This can be solved using an interactive rebase locally to "squash" all commits in 1, just like the UI here does but with the added benefit of running the checks again to make sure our commit message is compliant. This is necessary to enable automated changelog generation, that way I don't have any work after merging. I solved that for you, if you want more information on what/how, simply drop a message. Thanks for your contribution!

2023-11-01 07:36 UTC, merged

2023-11-01 11:00 UTC, JanDeDobbeleer commented
@all-contributors please add @mishmanners for doc

This is pure magic 🪄! @holopin-bot @mishmanners wizard