Pulumi segment
JanDeDobbeleer/oh-my-posh pull request #4650
Opened 2024-01-28 19:05 UTC by lzecca78

### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md].
- [x] The commit message follows the [conventional commits][cc] guidelines.
- [x] Tests for the changes have been added (for bug fixes / features).
- [x] Docs have been added/updated (for bug fixes / features).

### Description
The aim of this PR is to introduces a new segment for pulumi.
Hope to have put everything in the right place!
The pulumi segment will display user (when a user is logged in), url (for remote state) and the stack selected (if a stack is selected).
The PR modifies the following file: `src/engine/segment.go`, `themes/schema.json`, and `website/sidebars.js` and adds new files `src/segments/pulumi.go`, `src/segments/pulumi_test.go`, and `website/docs/segments/pulumi.mdx`

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

2024-01-30 14:38 UTC, kema-dev commented
Great idea, I would like to use this segment too !
Did you experience any performance issue ? I noticed that `pulumi about` is quite slow on my system (about 1.5 sec) and wonder if this is an issue with a om-my-posh segment ?

2024-01-30 15:42 UTC, JanDeDobbeleer commented
> wonder if this is an issue with a om-my-posh segment

@kema-dev definitely, this would need to be cached

2024-01-30 15:47 UTC, JanDeDobbeleer requested changes

2024-01-30 15:47 UTC, JanDeDobbeleer commented on src/segments/pulumi.go
> +func (p *Pulumi) setError(message string) {
I would remove this and log using `p.env.Error(message)` above. The whole `DisplayError` logic should be removed as it comes from a time where logging wasn't as good yet.

2024-01-30 15:47 UTC, JanDeDobbeleer commented on src/segments/pulumi.go
> +		return p.getPulumiStackName() && p.getPulumiAbout()
Do we need to make `fetch_about` and `fetch_stack` boolean properties? Now we always call this, but I can imagine not everyone wants to have that context.

2024-01-30 15:47 UTC, JanDeDobbeleer commented on src/segments/pulumi.go
> +	p.URL = about.Backend.URL
I would use the cache to store these rather than retrieve these values every time.

2024-01-30 15:47 UTC, lzecca78 commented
@JanDeDobbeleer @kema-dev  you are perfectly right, the issue with the cache, is the cache itself. It could be reasonably be enabled a sort of cache based on the stack name probably and with a 6 hours ttl? it could be reasonable for you?

2024-01-30 15:52 UTC, lzecca78 commented on src/segments/pulumi.go
> +	p.URL = about.Backend.URL
is there already an available cache implementation that can be used?

2024-01-30 15:56 UTC, JanDeDobbeleer commented
@lzecca78 the good news is that the cache timeout is easily configurable. So you can add a sane default for others to override.

2024-01-30 17:18 UTC, kema-dev commented
Pulumi stacks can change over time as it is just a selection of the current environment we would like to deploy to. Running `pulumi stack select <stack name>` alters this stack, and this command can be used pretty often when working on multi-stack projects, making me think that caching is not the right solution there.

Quickly analyzing trace of `pulumi stack <args>` made me think that such commands are making HTTP requests and parses retrieved information, this could explain the high amount of time those commands take.

However, I found [there](https://github.com/pulumi/pulumi/blob/master/sdk/go/common/workspace/paths.go#L266) that currently selected stack is tracked locally, and [there](https://github.com/pulumi/pulumi/blob/master/sdk/go/common/workspace/workspace.go#L191) how this file's path is computed. This gave me a path like `$HOME/.pulumi/workspaces/<project>-<hash>-workspace.json` with `project name` value found in current directory as value of the `name` key in `Pulumi.{yaml:json}`, and `hash` sha1sum of absolute path of the related `Pulumi.{yaml:json}` with filename included. This file contains the current stack name as value of `stack` key in the JSON.

Parsing the appropriate file would be much faster, I think that we can avoid caching by doing so as the necessary computations are fairly trivial.

2024-01-30 19:52 UTC, lzecca78 commented
@kema-dev, great! Nice catch! 
IMHO the cache can still be a solution. Given that in those files `$HOME/.pulumi/workspaces/<project>-sha-workspace.json` only contains the stack name, given that this file exists only once you've selected the stack and given that this doesn't solve the `pulumi about` command, maybe  cache can be still adopted with the following logic: 
`key: <project-stack> `
`value : <pulumi-about-output> `
Where project is taken, as you said, from the `Pulumi.{yaml:json}`  file in the directory of the project from the key `name` and the stack from the file you documented above.
So following the above example, once you have selected the stack (that is something that you have to do in a way or another manually), you can cache once per `project-stack` (that should be pretty unique key) the about output avoiding to hit the content,  _often_ . 
The only question is, _how much this cache should last?_ 1 day? 1 week?  
This could be a mixed solution that takes somehow in consideration your suggestions but still takes as main solution the cache that  from my point of view is still relevant given the time that the command takes.

2024-01-30 20:50 UTC, kema-dev commented
You are right, caching by stack seems a great idea !
Looking into [this](https://github.com/pulumi/pulumi/blob/master/sdk/go/common/workspace/creds.go#L169), it seems that credentials file could be handy. [Pulumi docs](https://www.pulumi.com/docs/concepts/state/) also suggests using `pulumi whoami`, might it be a local and fast command ? I might dig into this tomorrow !

2024-02-03 17:07 UTC, lzecca78 commented
hi @kema-dev  @JanDeDobbeleer ! 
Sorry for the delay but during the week is very hard to put hands on this. 
I've had heavily refactored pretty much everything accordingly with what we said in the conversation, is not finish yet the PR (in the happy path scenario I still have to update the doc accordingly with these changes)
When you have a chance, please give a look to what I did just to tell me what do you think

2024-02-03 17:26 UTC, kema-dev reviewed
Great work !

2024-02-03 17:26 UTC, kema-dev commented on src/segments/pulumi.go
> +	keyCache := project + "-" + p.Stack + "-about"
We might want to add a `pulumi-` prefix or w/e if `p.env.Cache()` is shared across all segments

2024-02-04 13:13 UTC, lzecca78 commented
@kema-dev ,  I was trying to test locally but for reason that I am not able to understand 🤔 , even if putting to the `Enabled()`  `return true` function in the pulumi segment, I always get Pulumi(false) in `oh-my-posh debug` command, although I've enabled it by adding this map into the configuration:

```json
        {
          "background": "#316ce4",
          "foreground": "#ffffff",
          "leading_diamond": "\ue0b6",
          "style": "diamond",
          "template": "\uf308 {{ .Stack }}{{if .User }} :: {{ .User }}@{{ end }}{{ if .URL }}{{ .URL }}{{ end }}",
          "trailing_diamond": "\ue0b4",
          "type": "pulumi"
        },
```

2024-02-04 22:13 UTC, kema-dev commented on src/segments/pulumi.go
> +	sha1HexString, err := p.sha1HexString(p.SpecFile.Path)
```suggestion
	sha1HexString, err := p.sha1HexString(p.SpecFile.Path + "/" + p.SpecFile.FileName)
```

This path should include the filename

2024-02-04 22:26 UTC, kema-dev commented on src/segments/pulumi.go
> +	}
```suggestion
	stackNameFileContent := p.env.FileContent(workspaceCacheFile)
	if len(stackNameFileContent) != 0 {
		var pulumiWorkspaceSpec PulumiWorkSpaceFileSpec
		err = json.Unmarshal([]byte(stackNameFileContent), &pulumiWorkspaceSpec)
		if err != nil {
			p.env.Error(fmt.Errorf("PULUMI STACK FILE DECODE ERROR"))
			return false
		}
		p.Stack = pulumiWorkspaceSpec.Stack
		return true

	}
```

`HasFiles` checks if the directory has trigger files, according to `display_mode` property, like [there](https://ohmyposh.dev/docs/segments/helm#properties), this should work as intended.

2024-02-04 22:29 UTC, kema-dev commented
@lzecca78 I am experiencing same behavior, I don't really know why :shrug: 

I could get a proper `Stack` name display within the segment with the suggested changes. Did not test the caching though

2024-02-05 07:54 UTC, lzecca78 commented
@kema-dev , thanks for tips, I've slightly adjusted the code (see https://github.com/JanDeDobbeleer/oh-my-posh/pull/4650/commits/06d9da555a7db5ff04dab583bbc702a1503681f2) and fixed wrong behavior with cache when the cache wasn't hit, now everything seems working perfectly 🎉 !

2024-02-06 18:11 UTC, kema-dev approved these changes
LGTM, very nice work ! I'm happy to be able to use this segment

Just added some logging in code and added what look like mispelling in tests

2024-02-06 18:11 UTC, kema-dev commented on src/segments/pulumi_test.go
> +			ExpectedString:           stackName,
```suggestion
				"and pulumi about is present, but no user and url properties",
```

2024-02-06 18:11 UTC, kema-dev commented on src/segments/pulumi_test.go
> +			ExpectedString:           stackName + " :: posh-user@s3://test-pulumi-state-test",
```suggestion
				"pulumi about is present with user and url properties but no cache",
```

2024-02-06 18:11 UTC, kema-dev commented on src/segments/pulumi_test.go
> +			ExpectedString:           stackName + " :: posh-user@s3://test-pulumi-state-test",
```suggestion
				"pulumi about is present with user and url properties with cache hit",
```

2024-02-06 18:11 UTC, kema-dev commented on src/segments/pulumi.go
> +		}
```suggestion
			p.env.Debug("PULUMI ABOUT CACHE HAS BACKEND EMPTY")
		}
```

2024-02-06 18:11 UTC, kema-dev commented on src/segments/pulumi.go
> +		return false
```suggestion
		p.env.Debug("PULUMI ABOUT CACHE HAS NO BACKEND")
		return false
```

2024-02-06 18:11 UTC, kema-dev commented on src/segments/pulumi.go
> +		return false
```suggestion
		p.env.Error(fmt.Errorf("PULUMI ABOUT HAS INVALID BACKEND"))
		return false
```

2024-02-06 18:11 UTC, kema-dev commented on src/segments/pulumi.go
> +		return false
```suggestion
		p.env.Error(fmt.Errorf("PULUMI STACK NAME IS EMPTY"))
		return false
```

2024-02-06 18:11 UTC, kema-dev approved these changes
LGTM, very nice work! I'm happy to be able to use this segment!

Just added some logging in code and added what look like misspelling in tests

2024-02-17 05:25 UTC, lzecca78 commented
Hi @JanDeDobbeleer , just ping to understand if there is still something that I need to improve or to be reviewed. Let me know so I can do changes accordingly to that. Thanks 🙏

2024-02-19 08:03 UTC, JanDeDobbeleer commented
@lzecca78 sorry, been crazy busy and this review was lower on my prio list 😓 Will have a look this week.

2024-02-26 07:44 UTC, JanDeDobbeleer commented
@lzecca78 I pushed my changes, can you validate this still works as designed?

2024-02-26 10:52 UTC, lzecca78 commented
@JanDeDobbeleer , I didn't have a lot of time, but I've tried testing it directly and is working partially. the `about` section unfortunately is not working 😞 , while in my previous implementation works. Another weird stuff happens when you do `oh-my-posh debug` that I see the pulumi segment `off` although is active and working fine 🤔

2024-02-26 10:54 UTC, JanDeDobbeleer commented
@lzecca78 did you change the properties to use the new naming? Because that could still be the issue. `oh-my-posh debug` should indicate the same as the prompt when in the same folder.

2024-02-26 10:56 UTC, lzecca78 commented
@JanDeDobbeleer , yes I did it, otherwise neither the stack name was visible 👍

2024-02-26 10:57 UTC, JanDeDobbeleer commented
@lzecca78 can you share the logs?

2024-02-27 11:17 UTC, lzecca78 commented
@JanDeDobbeleer the output of `oh-my-posh debug` you mean?

2024-02-27 11:23 UTC, JanDeDobbeleer commented
Yes!

2024-02-27 14:41 UTC, lzecca78 commented
@JanDeDobbeleer i saw the log, but there isn't any reference to pulumi. Even the prompt:

```
Prompt:

╭─ zsh  pippo    feat/pippo-pluto ≡  ?1  0ms⠀                                                                            it@eu-west-1  example-staging :: posh    100   27,15:27 
╰─
```
is not the real one (i have the pulumi stack in the prompt, but I dunno why is not rendered in the log.
And in the segment list, pulumi is false

```

Segments:

ConsoleTitle(false) -   0 ms
Shell(true)         -   1 ms
Root(false)         -   0 ms
Path(true)          -   1 ms
Git(true)           -  35 ms
Executiontime(true) -   1 ms
Node(false)         -   3 ms
Python(false)       -   1 ms
Java(false)         -   3 ms
Dotnet(false)       -   3 ms
Go(false)           -   1 ms
Rust(false)         -   2 ms
Dart(false)         -   1 ms
Angular(false)      -   1 ms
Nx(false)           -   1 ms
Julia(false)        -   0 ms
Ruby(false)         -   2 ms
Azfunc(false)       -   2 ms
Aws(true)           -   0 ms
Kubectl(true)       -  32 ms
Pulumi(false)       -   0 ms
Os(true)            -   0 ms
Battery(true)       -  19 ms
Time(true)          -   0 ms
Text(true)          -   0 ms
Status(true)        -   0 ms
```


In the other logs lines, there is no any traces of the pulumi logs that should be present. ( I avoid to paste them here because they don't contain any meaningful information for debugging the pulumi segment)

2024-02-27 19:56 UTC, JanDeDobbeleer commented
@lzecca78 I would really love the logs so I can have a look. If there's nothing relevant regarding pulumi, that could also indicate it's a version of oh-my-posh without that segment logic.

2024-02-28 08:08 UTC, lzecca78 commented
@JanDeDobbeleer the segment is there, but as you can see keeps putting `false` in the segment, although is working (partially with your changes, but fully working with my previous version). TBH I dunno why is behaving like that. The problem of the logs is that I have to send you incomplete logs because most of them contains sensible informations (dumps of aws credentials, as well as dump of kubeconfig and other stuff). So here the logs without all the sensible infos:

```
Version: 19.8.2

Shell: zsh (5.9)

Prompt:

╭─ zsh  pippo    feat/pippo-pluto ≡  ?1  0ms⠀                                                                            it@eu-west-1  example-staging :: posh    100   27,15:27 
╰─

Config path: /Users/user/oh-my-posh/themes/atomic.omp.json

Logs:

[DEBUG] 15:27:48.273 shell.go:Getenv:399 → NO DATA
[TRACE] 15:27:48.273 shell.go:Getenv(TERM_PROGRAM) - 783.917µs
[DEBUG] 15:27:48.273 shell.go:Getenv:399 → NO DATA
[TRACE] 15:27:48.273 shell.go:Getenv(OMP_CACHE_DIR) - 1.709µs
[DEBUG] 15:27:48.273 shell.go:Getenv:399 → NO DATA
[TRACE] 15:27:48.273 shell.go:Getenv(XDG_CACHE_HOME) - 1.583µs
[TRACE] 15:27:48.273 shell_unix.go:CachePath() - 39.167µs
[DEBUG] 15:27:48.276 shell.go:Getenv:399 → /Users/user/oh-my-posh/themes/atomic.omp.json
[TRACE] 15:27:48.276 shell.go:Getenv(POSH_THEME) - 2.792µs
[DEBUG] 15:27:48.276 shell_unix.go:Platform:77 → darwin
[TRACE] 15:27:48.276 shell.go:resolveConfigPath() - 191.917µs
[TRACE] 15:27:48.276 shell.go:Init() - 3.655834ms
[TRACE] 15:27:48.276 shell.go:Flags() - 41ns
[TRACE] 15:27:48.280 config.go:loadConfig() - 3.1425ms
[TRACE] 15:27:48.280 shell.go:Flags() - 42ns
[DEBUG] 15:27:48.280 shell.go:Getenv:399 → NO DATA
[TRACE] 15:27:48.280 shell.go:Getenv(OMP_CACHE_DISABLED) - 2.625µs
[DEBUG] 15:27:48.280 shell.go:Shell:662 → no shell name provided in flags, trying to detect it
[DEBUG] 15:27:48.280 shell.go:Shell:670 → process name: zsh
[TRACE] 15:27:48.280 shell.go:Shell() - 367.5µs
[DEBUG] 15:27:48.280 shell.go:Getenv:399 → 5.9
[TRACE] 15:27:48.280 shell.go:Getenv(POSH_SHELL_VERSION) - 1.292µs
[DEBUG] 15:27:48.280 debug.go:PrintDebug:22 → Segment: Title
[DEBUG] 15:27:48.281 text.go:Render:70 → Rendering template:
[DEBUG] 15:27:48.281 shell.go:Getenv:399 → NO DATA
[TRACE] 15:27:48.281 shell.go:Getenv(POSH_CURSOR_LINE) - 11.834µs
[DEBUG] 15:27:48.281 shell.go:Getenv:399 → NO DATA
[TRACE] 15:27:48.281 shell.go:Getenv(POSH_CURSOR_COLUMN) - 1.083µs
[TRACE] 15:27:48.281 shell.go:Flags() - 0s
[TRACE] 15:27:48.281 shell.go:Flags() - 0s
[TRACE] 15:27:48.281 shell.go:Shell() - 41ns
[TRACE] 15:27:48.281 shell.go:Shell() - 42ns
[TRACE] 15:27:48.281 shell.go:Flags() - 42ns
[TRACE] 15:27:48.281 shell.go:Flags() - 83ns
[TRACE] 15:27:48.281 shell.go:Flags() - 125ns
[TRACE] 15:27:48.281 shell.go:Flags() - 500ns
[TRACE] 15:27:48.281 shell.go:Flags() - 83ns
[TRACE] 15:27:48.281 shell.go:GOOS() - 41ns
[TRACE] 15:27:48.281 shell.go:Pwd() - 34.542µs
[TRACE] 15:27:48.281 shell.go:GOOS() - 0s
[DEBUG] 15:27:48.281 segment.go:SetEnabled:518 → Segment: Git
[TRACE] 15:27:48.281 shell.go:Pwd() - 375ns
[TRACE] 15:27:48.281 shell.go:GOOS() - 42ns
[DEBUG] 15:27:48.281 segment.go:SetEnabled:518 → Segment: Shell
[TRACE] 15:27:48.281 shell.go:Pwd() - 125ns
[TRACE] 15:27:48.281 shell.go:GOOS() - 41ns
[DEBUG] 15:27:48.281 segment.go:SetEnabled:518 → Segment: Root
[TRACE] 15:27:48.281 shell.go:Pwd() - 83ns
[TRACE] 15:27:48.281 shell.go:GOOS() - 42ns
[DEBUG] 15:27:48.281 segment.go:SetEnabled:518 → Segment: Path
[TRACE] 15:27:48.281 shell.go:Pwd() - 125ns
[TRACE] 15:27:48.281 shell.go:GOOS() - 41ns
[DEBUG] 15:27:48.281 shell_unix.go:IsWsl:35 → false
[DEBUG] 15:27:48.281 segment.go:SetEnabled:518 → Segment: Executiontime
[TRACE] 15:27:48.281 shell_unix.go:IsWsl2() - 7.292µs
[TRACE] 15:27:48.281 shell_unix.go:Root() - 667ns
[TRACE] 15:27:48.281 shell.go:GOOS() - 41ns
[TRACE] 15:27:48.281 shell.go:Pwd() - 0s
[TRACE] 15:27:48.281 shell.go:Shell() - 83ns
[TRACE] 15:27:48.281 shell.go:Shell() - 41ns
[DEBUG] 15:27:48.281 properties.go:GetBool:22 → always_enabled: false
[DEBUG] 15:27:48.281 properties.go:GetKeyValueMap:46 → mapped_shell_names: map[]
[TRACE] 15:27:48.281 shell.go:ExecutionTime() - 42ns
[TRACE] 15:27:48.281 shell.go:Shell() - 83ns
[TRACE] 15:27:48.281 shell.go:Flags() - 42ns
[DEBUG] 15:27:48.281 properties.go:GetFloat64:34 → threshold: 0.000000
[TRACE] 15:27:48.281 shell_unix.go:Root() - 333ns
[TRACE] 15:27:48.281 shell.go:Shell() - 0s
[TRACE] 15:27:48.281 shell.go:StatusCodes() - 84ns
[DEBUG] 15:27:48.281 shell_unix.go:IsWsl:35 → false
[TRACE] 15:27:48.281 shell_unix.go:IsWsl() - 1.667µs
[DEBUG] 15:27:48.281 properties.go:GetString:28 → roundrock
[DEBUG] 15:27:48.282 shell.go:CommandPath:615 → /opt/homebrew/bin/git
[TRACE] 15:27:48.282 shell.go:CommandPath(git) - 148.459µs
[TRACE] 15:27:48.282 shell.go:HasCommand(git) - 150.042µs
[TRACE] 15:27:48.282 shell.go:Pwd() - 84ns
[DEBUG] 15:27:48.281 properties.go:GetBool:22 → mapped_locations_enabled: true
[DEBUG] 15:27:48.282 properties.go:GetString:28 → 
[DEBUG] 15:27:48.282 properties.go:GetString:28 → 
[TRACE] 15:27:48.282 shell.go:GOOS() - 0s
[DEBUG] 15:27:48.282 properties.go:GetKeyValueMap:46 → mapped_locations: map[]
[TRACE] 15:27:48.282 shell.go:PathSeparator() - 42ns
[TRACE] 15:27:48.282 shell.go:GOOS() - 0s
[TRACE] 15:27:48.282 shell.go:HasParentFilePath(.git) - 41.291µs
[TRACE] 15:27:48.282 shell.go:GOOS() - 42ns
[TRACE] 15:27:48.282 shell.go:Pwd() - 42ns
[DEBUG] 15:27:48.282 properties.go:GetStringArray:52 → exclude_folders: []
[TRACE] 15:27:48.282 shell.go:GOOS() - 42ns
[TRACE] 15:27:48.282 shell.go:GOOS() - 42ns
[TRACE] 15:27:48.282 shell.go:GOOS() - 0s
[TRACE] 15:27:48.282 shell.go:GOOS() - 41ns
[TRACE] 15:27:48.282 shell.go:GOOS() - 0s
[TRACE] 15:27:48.282 shell.go:GOOS() - 41ns
[DEBUG] 15:27:48.282 properties.go:GetBool:22 → fetch_user: false
[TRACE] 15:27:48.282 shell.go:GOOS() - 41ns
[TRACE] 15:27:48.282 shell.go:GOOS() - 42ns
[TRACE] 15:27:48.282 shell.go:GOOS() - 0s
[TRACE] 15:27:48.282 shell.go:GOOS() - 0s
[TRACE] 15:27:48.282 shell.go:GOOS() - 0s
[TRACE] 15:27:48.282 shell.go:GOOS() - 0s
[TRACE] 15:27:48.282 shell.go:GOOS() - 42ns
[TRACE] 15:27:48.282 shell.go:GOOS() - 0s
[TRACE] 15:27:48.282 shell.go:GOOS() - 41ns
[TRACE] 15:27:48.282 shell.go:GOOS() - 0s
[DEBUG] 15:27:48.282 shell.go:User:564 → user
[TRACE] 15:27:48.282 shell.go:GOOS() - 0s
[TRACE] 15:27:48.282 shell.go:User() - 1.291µs
[TRACE] 15:27:48.282 shell.go:GOOS() - 41ns
[TRACE] 15:27:48.282 shell.go:GOOS() - 41ns
[TRACE] 15:27:48.282 shell.go:GOOS() - 42ns
[TRACE] 15:27:48.282 shell.go:GOOS() - 0s
[TRACE] 15:27:48.282 shell.go:GOOS() - 0s
[TRACE] 15:27:48.282 shell.go:GOOS() - 0s
[TRACE] 15:27:48.282 shell.go:GOOS() - 42ns
[TRACE] 15:27:48.282 shell.go:GOOS() - 42ns
[TRACE] 15:27:48.282 shell.go:GOOS() - 0s
[TRACE] 15:27:48.282 shell.go:PathSeparator() - 0s
[TRACE] 15:27:48.282 shell.go:GOOS() - 42ns
[DEBUG] 15:27:48.282 shell.go:Host:576 → M-PA-QD1P7D224P
[DEBUG] 15:27:48.282 shell.go:Getenv:399 → NO DATA
[TRACE] 15:27:48.282 shell.go:GOOS() - 0s
[TRACE] 15:27:48.282 shell.go:Getenv(POSH_GIT_STATUS) - 1.167µs
[TRACE] 15:27:48.282 shell.go:PathSeparator() - 42ns
[TRACE] 15:27:48.282 shell.go:GOOS() - 0s
[TRACE] 15:27:48.282 shell.go:GOOS() - 42ns
[DEBUG] 15:27:48.282 properties.go:GetBool:22 → fetch_status: true
[TRACE] 15:27:48.282 shell.go:GOOS() - 41ns
[DEBUG] 15:27:48.282 shell.go:Getenv:399 → 1
[TRACE] 15:27:48.282 shell.go:PathSeparator() - 41ns
[TRACE] 15:27:48.282 shell.go:Getenv(SHLVL) - 1.417µs
[TRACE] 15:27:48.282 shell.go:GOOS() - 0s
[TRACE] 15:27:48.282 shell.go:GOOS() - 42ns
[TRACE] 15:27:48.282 shell.go:TemplateCache() - 129.291µs
[TRACE] 15:27:48.282 shell.go:PathSeparator() - 0s
[TRACE] 15:27:48.282 shell.go:PathSeparator() - 0s
[DEBUG] 15:27:48.282 properties.go:GetString:28 → folder
[TRACE] 15:27:48.282 shell.go:TemplateCache() - 119.875µs
[TRACE] 15:27:48.282 shell.go:GOOS() - 41ns
[TRACE] 15:27:48.282 shell.go:GOOS() - 0s
[TRACE] 15:27:48.282 shell.go:GOOS() - 0s [...]

2024-02-28 08:32 UTC, JanDeDobbeleer commented
@lzecca78 why is your version `Version: 19.8.2`? Did you build with the same version number? Because I'd expect `development` here as that's the default value.

2024-02-29 15:32 UTC, lzecca78 commented
@JanDeDobbeleer , probably i locally recompiled without changing the version, but it shouldn't affect the behavior, isn't it?

2024-02-29 15:50 UTC, JanDeDobbeleer commented
@lzecca78 but that's not possible, the version isn't part of the code. So if you didn't set it, I'm quite certain you're using a production release without that code.

2024-02-29 16:01 UTC, lzecca78 commented
i've did `go build -o oh-my-posh` inside the `src/` dir without changing the version tbh

2024-02-29 17:00 UTC, JanDeDobbeleer commented
@lzecca78 yes, but them the output of `oh-my-posh version` needs to be `development` (also for the logs) and not `Version: 19.8.2`. So, you're not testing with that build is what I'm saying.

2024-03-01 13:32 UTC, kema-dev commented
@lzecca78 I think that what Jan means is that, based on your `$PATH`, your `oh-my-posh` command is your globally installed binary, not the one you built using `go build`. Locally, running `oh-my-posh debug` on a binary built from your up-to-date PR prints `Pulumi(true)`, and `Version:` (no version). However, no `{{ .Stack }}` is printed in the prompt.

2024-03-11 17:46 UTC, lzecca78 commented
@JanDeDobbeleer @kema-dev , you were right, to invoke the `oh-my-posh debug` I was not passing the full path of the compiled binary, and for this reason having those logs, sorry for the misunderstanding on that. Anyway, AFAIK I've tested it again locally,  and I've found an issue with caching that I've fixed. Now it works as expected!

2024-03-11 17:47 UTC, JanDeDobbeleer commented
@lzecca78 so this can be merged?

2024-03-11 17:49 UTC, lzecca78 commented
Maybe we should check if linting/testing is ok and ✅ , but on top of that, for me yes 👍

2024-03-11 17:57 UTC, kema-dev commented
I still get `False` for the segment, with relevant trace here:
```log
[TRACE] 18:54:40.297 shell.go:HasFilesInDir(Pulumi.json) - 11.65µs
[ERROR] 18:54:40.297 pulumi.go:Enabled:67 → no pulumi spec file found
```

2024-03-11 18:08 UTC, lzecca78 commented
> I still get `False` for the segment, with relevant trace here:
> ```log
> [TRACE] 18:54:40.297 shell.go:HasFilesInDir(Pulumi.json) - 11.65µs
> [ERROR] 18:54:40.297 pulumi.go:Enabled:67 → no pulumi spec file found
> ```

In my case using the right binary compiled the segment is set to true

2024-03-11 18:31 UTC, kema-dev commented
> > I still get `False` for the segment, with relevant trace here:
> > ```
> > [TRACE] 18:54:40.297 shell.go:HasFilesInDir(Pulumi.json) - 11.65µs
> > [ERROR] 18:54:40.297 pulumi.go:Enabled:67 → no pulumi spec file found
> > ```
> 
> In my case using the right binary compiled the segment is set to true

Double my bad:
- `Pulumi(False)` was caused by not being in a "pulumi project dir", no `Pulumi.{yaml,json}` present
- Had no stack info because I had old values in my theme, I noticed you now have `fetch_stack` and `fetch_about` but was using `pulumi_user` and `pulumi_url`

Everything works fine ! Switching stack works, caching as needed.

LGTM !

And thank you / well done though ! :heart:

2024-03-13 08:10 UTC, lzecca78 commented
@JanDeDobbeleer I've reworded the commits accordingly with the commitlint Github Workflow, now it could be merged I guess

2024-03-13 11:46 UTC, JanDeDobbeleer approved these changes

2024-03-14 07:47 UTC, merged

2024-03-14 07:48 UTC, JanDeDobbeleer commented
@all-contributors please add @lzecca78 for code,design,doc

This is pure magic 🪄! @holopin-bot @lzecca78 wizard