docs: add chocolatey as an install method for windows
JanDeDobbeleer/oh-my-posh pull request #4661
Opened 2024-02-03 16:51 UTC by VEERT00X

### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md].
- [x] The commit message follows the [conventional commits][cc] guidelines.
- [ ] Tests for the changes have been added (for bug fixes / features).
- [x] Docs have been added/updated (for bug fixes / features).

### Description

This pull request aims to address #4654 and focuses on improving the documentation by including information about using Chocolatey as an installation and update method for [Oh My Posh](https://ohmyposh.dev/) on Windows.

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

2024-02-03 19:15 UTC, st3phhays requested changes
Hi there, this is awesome you got a PR in for this. I was the one who raised the issue and am part of the Chocolatey team. 😄 

Would you mind updating the tab label to say "chocolatey" instead of "choco"? I haven't ran this, but I'm assuming this is what shows up for the tab labels at the top. I'm unsure if the value would need to be updated as well, or if it is ok if that still says "choco". The end goal is to have the tab read as "chocolatey".

2024-02-03 19:15 UTC, st3phhays commented on website/docs/installation/windows.mdx
> +    { label: 'choco', value: 'choco'},
```suggestion
    { label: 'chocolatey', value: 'choco'},
```

2024-02-03 19:15 UTC, st3phhays commented on website/docs/installation/windows.mdx
> +    { label: 'choco', value: 'choco'},
Same here.

```suggestion
    { label: 'chocolatey', value: 'choco'},
```

2024-02-03 20:24 UTC, VEERT00X commented on website/docs/installation/windows.mdx
> +    { label: 'choco', value: 'choco'},
Done

2024-02-03 20:35 UTC, VEERT00X reviewed
I have changed the **"label"** _choco_ to _chocolatey_, and refactored the changes to be in the same style as the other labels (label and value are the same). The end result remains the same.

This was tested in a **node** [devcontainer](https://containers.dev/) under **Windows 11 Ubuntu WSL**

---

![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/72668825/3e570289-dc01-4a90-8c53-2c7be8ca958e)
![image](https://github.com/JanDeDobbeleer/oh-my-posh/assets/72668825/15000b33-ca50-435c-a231-542ea463bbc4)

2024-02-03 22:50 UTC, st3phhays approved these changes
This LGTM! Thanks for making those changes. 👍

2024-02-04 13:32 UTC, JanDeDobbeleer commented
I'm just going to change a few things as this package isn't officially supported by me. And i was always reluctant to add stuff the docs I can't control 100%.

2024-02-04 13:34 UTC, VEERT00X commented
Sure

2024-02-04 13:46 UTC, closed without merging

2024-02-04 13:52 UTC, JanDeDobbeleer commented
@all-contributors please add @VEERT00X for doc

This is pure magic 🪄! @holopin-bot @VEERT00X wizard