Spotify segment (linux)
JanDeDobbeleer/oh-my-posh pull request #4732
Opened 2024-03-03 10:17 UTC by luisegarduno

### Prerequisites

- [X] I have read and understood the [contributing guide](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md).
- [X] The commit message follows the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) guidelines.
- [X] Tests for the changes have been added (for bug fixes / features).
- [X] Docs have been added/updated (for bug fixes / features).

### Description

The goal of this PR is to create a *working* segment that displays the song & artist currently playing on the Spotify application via Linux.

![mytheme](https://github.com/JanDeDobbeleer/oh-my-posh/assets/30121656/c5beefe6-b07c-4432-be47-6ded140c0541)

I created a solution to fetch information from the Spotify application on Linux (Ubuntu) by using a bash segment to run a command. Having said this, the command is written directly in the theme file (see [gist](https://gist.github.com/luisegarduno/a1f0b76d3f0d2e18079de089d04dae69#file-blurry-omp-json-L127-L140)).

About 2 years ago, I forked oh-my-posh with the intention of converting the command into a proper segment, but never got around to getting it to work. Given my limited experience with go, I figured I should ask for help. 

Regarding the solution itself, here is the command that retrieves the Spotify information:
```bash
$ dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata
```

The command shown above has been tested on several Ubuntu machines and has show to work consistently well. However, I am uncertain on the compatibility across other Linux distributions.

2024-03-04 13:12 UTC, JanDeDobbeleer commented
Cool! This isn't a bad start. Allow me to review that somewhere this week.

2024-03-14 07:38 UTC, JanDeDobbeleer requested changes
We need to also update the docs, and eventually probably add a `source` property too specifying `dbus` or something else (but that's not relevant now)

2024-03-14 07:38 UTC, JanDeDobbeleer commented on src/segments/spotify_linux.go
> +	tlist := s.env.RunShellCommand(shell.BASH, command)
```suggestion
	tlist := s.env.RunCommand("dbus-send", "--print-reply", "--dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata")
```

2024-03-20 17:50 UTC, luisegarduno commented on src/segments/spotify_linux.go
> +	tlist := s.env.RunShellCommand(shell.BASH, command)
Resolved using:
```go
tlist, _ := s.env.RunCommand("dbus-send", "--print-reply", "--dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata")
```

2024-03-20 17:55 UTC, luisegarduno commented
I'm able to get the tests to pass locally, however when testing the binary, the spotify segment is not showing.

2024-03-24 15:59 UTC, JanDeDobbeleer commented
> I'm able to get the tests to pass locally, however when testing the binary, the spotify segment is not showing.

You can use `oh-my-posh debug `to show what’s going on.

2024-04-01 08:15 UTC, JanDeDobbeleer commented
@luisegarduno any update?

2024-04-06 23:53 UTC, luisegarduno commented
Thanks for tip, `oh-my-posh debug` has been very helpful.

I've made some progress in my latest commit, having `{{.Artist}} - {{.Track}}` now work.

The workflow will not get far though, as I deleted `spotify_wsl` & `spotify_wsl_test` (locally) so that I could get `spotify_linux` to build - matching boolean function names "***Enabled***". I assume this may be an easy fix, as I just need to figure out a way to separate the builds for wsl & linux since `//go:build wsl` isn't a thing yet.

2024-08-10 15:24 UTC, luisegarduno commented
Haven't made much progress so I figured I would clarify the issue just in case someone is able to figure it out before I do.

As mentioned in my last response, I have been able to verify `spotify_linux.go` works & passes its tests by temporarily deleting `spotify_wsl.go` & `spotify_wsl_test.go`. I have been unable to figure out a way to get both `spotify_linux` & `spotify_wsl` to work without having to delete one or the other.

-----------------------------
<h3>WSL</h3>

* [spotify_wsl.go](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/segments/spotify_wsl.go#L1-L9):
```go
//go:build !darwin && !windows

...

func (s *Spotify) Enabled() bool {
```

<h3>Linux</h3>
 
* [spotify_linux.go](https://github.com/luisegarduno/oh-my-posh/blob/main/src/segments/spotify_linux.go#L1-L11):
```go
//go:build linux && !darwin && !windows

...

func (s *Spotify) Enabled() bool {
```
------------------------

Error:
```text
method Spotify.Enabled already declared at oh-my-posh/src/segments/spotify_linux.go:11:19compiler
```

------------------

I have a feeling that adding the `wsl` expression (*see below*) would fix the error:
* *spotify_linux.go*: `//go:build linux && !darwin && !windows && !wsl`
  * This would constrain it to build on Linux but not on WSL (`!wsl`)
* *spotify_wsl.go*: `//go:build linux && !darwin && !windows && wsl`
  * This would constrain it to build on Linux specifically within WSL (`wsl`)

However, I am not sure how I would go about implementing `wsl` as a build constraint.
* [[Go](https://pkg.go.dev/go/build)]: build package - go/build - Go Packages
* [[Go](https://pkg.go.dev/cmd/go#hdr-Build_constraints)]: go command - cmd/go - Go Packages

Any help would be appreciated! :smiley_cat:

2025-03-22 07:31 UTC, luisegarduno commented
Resolve the issue I was having with overlapping *linux* build tags (*linux*) by moving `spotify_wsl.go` into `spotify_linux.go`. 

All `.Status` states (playing/paused/stopped) are supported.

2025-03-30 14:56 UTC, JanDeDobbeleer commented
@luisegarduno this one's on my list for tomorrow during lunch.

2025-03-30 14:59 UTC, JanDeDobbeleer commented on themes/luis.omp.json
this is a sneaky addition as we don't allow new themes anymore :-)

2025-03-30 15:07 UTC, JanDeDobbeleer commented
@all-contributors please add @luisegarduno for code

This is pure magic 🪄! @holopin-bot @luisegarduno wizard

2025-03-30 15:07 UTC, JanDeDobbeleer commented
will be merged with #6321

2025-03-30 15:13 UTC, luisegarduno commented on themes/luis.omp.json
boo hehe

2025-03-30 15:28 UTC, closed without merging