feat: Firebase Segment
JanDeDobbeleer/oh-my-posh pull request #4840
Opened 2024-04-15 22:17 UTC by ivan-the-terrible

### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md].
- [x] The commit message follows the [conventional commits][cc] guidelines.
- [x] Tests for the changes have been added (for bug fixes / features).
- [x] Docs have been added/updated (for bug fixes / features).

### Description

After discovering a user who created a custom script to show the current Firebase project, the need for a real Firebase segment came to light.
Here is the original script invoking the idea: https://github.com/QuentinPhrl/Omp_firebase_prompt

The segment, its tests, its required references like in schema and in the engine, and the proper documentation have all been added.

### Firebase Segment

In short, here is how the segment works:

Once a user has installed the `firebase-tools` CLI npm package, they can initialize and connect a Firebase project.

The CLI tool creates `~/.config/configstore/firebase-tools.json` file and any directory that has had `firebaes init` ran on it and a project associated with it, gets added to the JSON file via the `activeProjects` property. This property has the path as the key and the project name as the value.

[INSERT IMAGE]

If the Firebase segment is active, we are checking that `activeProjects` map to see if the curent directory exists in there. If it does, we display the project name in the segment.

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

2024-04-17 07:34 UTC, JanDeDobbeleer requested changes

2024-04-17 07:34 UTC, JanDeDobbeleer commented on src/segments/firebase.go
> +	cfgDir := path.Join(f.env.Home(), ".config", "configstore")
```suggestion
	cfgDir := filepath.Join(f.env.Home(), ".config", "configstore")
```

2024-04-17 07:34 UTC, JanDeDobbeleer commented on src/segments/firebase.go
> +	data, err := f.getFirebaseData(configFile)
add a space for readability between these blocks

2024-04-17 07:34 UTC, JanDeDobbeleer commented on src/segments/firebase.go
> +	return false
add a space for readability before `return false`

2024-04-17 07:34 UTC, JanDeDobbeleer commented on src/segments/firebase.go
> +	activeConfigFile := path.Join(cfgDir, "firebase-tools.json")
```suggestion
	activeConfigFile := filepath.Join(cfgDir, "firebase-tools.json")
```

2024-04-17 07:34 UTC, JanDeDobbeleer commented on src/segments/firebase.go
> +	FirebaseData
We shouldn't expose this, right?

2024-04-17 07:34 UTC, JanDeDobbeleer commented on src/segments/firebase.go
> +	err := json.Unmarshal([]byte(configFile), &data)
```suggestion

	err := json.Unmarshal([]byte(configFile), &data)
```

2024-04-17 07:34 UTC, JanDeDobbeleer commented on src/segments/firebase.go
> +	return &data, nil
```suggestion

	return &data, nil
```

2024-04-17 11:53 UTC, ivan-the-terrible commented on src/segments/firebase.go
> +	return false
Done

2024-04-17 11:54 UTC, ivan-the-terrible commented on src/segments/firebase.go
> +	cfgDir := path.Join(f.env.Home(), ".config", "configstore")
Updated to `filepath`

2024-04-17 11:54 UTC, ivan-the-terrible commented on src/segments/firebase.go
> +	data, err := f.getFirebaseData(configFile)
Space added

2024-04-17 11:54 UTC, ivan-the-terrible commented on src/segments/firebase.go
> +	activeConfigFile := path.Join(cfgDir, "firebase-tools.json")
Updated to `filepath`

2024-04-17 11:55 UTC, ivan-the-terrible commented on src/segments/firebase.go
> +	return &data, nil
Added space

2024-04-17 11:55 UTC, ivan-the-terrible commented on src/segments/firebase.go
> +	err := json.Unmarshal([]byte(configFile), &data)
added space

2024-04-17 12:02 UTC, ivan-the-terrible commented on src/segments/firebase.go
> +	FirebaseData
Totally right, it's unnecessary to expose it. I think I grabbed that idea from another segment.
Nonetheless, it's been removed

2024-04-18 12:51 UTC, merged

2024-04-18 12:51 UTC, JanDeDobbeleer commented
@all-contributors please add @ivan-the-terrible for code