Update faq.mdx
JanDeDobbeleer/oh-my-posh pull request #5100
Opened 2024-06-17 00:32 UTC by evo-ksalter

docs: Added a description on an issue with Visual Studio Code where ASCII escape codes are displayed after switching to Oh My Posh, and a solution.

### Prerequisites

- [X] I have read and understood the [contributing guide][CONTRIBUTING.md].
- [X] The commit message follows the [conventional commits][cc] guidelines.
- [X] Tests for the changes have been added (for bug fixes / features).
- [X] Docs have been added/updated (for bug fixes / features).

### Description

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

2024-06-17 06:34 UTC, JanDeDobbeleer commented
@evo-ksalter where do you get this fix from? Because the issue originates from their terminal integrations features which needs to be disabled using:

```json
{
  "terminal.integrated.shellIntegration.enabled": false
}
```

2024-06-17 11:50 UTC, evo-ksalter commented
@JanDeDobbeleer I linked the source in my update.  Here it is:

https://stackoverflow.com/questions/78468557/unexpected-ansi-escape-codes-on-vs-code-integrated-terminal

2024-06-18 12:04 UTC, JanDeDobbeleer requested changes

2024-06-18 12:04 UTC, JanDeDobbeleer commented on website/docs/faq.mdx
> +"args": [
the actual solution is to disable shell integrations and restart vscode:

{
  "terminal.integrated.shellIntegration.enabled": false
}

2024-06-20 05:28 UTC, closed without merging

2024-06-20 05:29 UTC, JanDeDobbeleer commented
Fixed in the latest release ofvscode