feat: Add 'random' segment
JanDeDobbeleer/oh-my-posh pull request #5457
Opened 2024-08-16 02:25 UTC by oliviaBahr

### Prerequisites

- [x] I have read and understood the [contributing guide][CONTRIBUTING.md].
- [x] The commit message follows the [conventional commits][cc] guidelines.
- [x] Tests for the changes have been added (for bug fixes / features).
- [x] Docs have been added/updated (for bug fixes / features).

### Description
Add a segment called Random which selects a random string from a list to display.

I wasn't sure which category to put this segment in, so I made a new one called `Miscellaneous` (We could also call it `Other`).
If we do add this category, I would probably move the `Text` segment there as well. Happy to add that to this pr or make a new one.

I couldn't figure out how to get the test config to persist in my env, so I've only actually seen it work when calling
`oh-my-posh print primary --config`
But so long as .Enabled() is called every time the prompt is rendered then it will work. I assume .Enabled() is called every time, because that's where the `Time` segment updates its info.

[CONTRIBUTING.md]: https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/CONTRIBUTING.md
[cc]: https://www.conventionalcommits.org/en/v1.0.0/#summary

2024-09-12 04:50 UTC, JanDeDobbeleer requested changes
@oliviaBahr thank you so much for this PR and your patience in me getting back to you. I feel like this would be a perfect [template function](https://github.com/JanDeDobbeleer/oh-my-posh/blob/ebe2cca2329243db26dca884e7eca0a8886af062/src/template/func_map.go#L10) instead of a segment as that's easy to use and leverage cross segment. We could even make the signature work with any type (if that's possible).

2024-09-19 19:17 UTC, JanDeDobbeleer commented
@oliviaBahr this is absolutely perfect. I have one remark, but overall 👍

2024-09-19 19:18 UTC, JanDeDobbeleer requested changes

2024-09-19 19:18 UTC, JanDeDobbeleer commented on src/template/random.go
> +	}
Can you add a newline here

2024-09-19 19:18 UTC, JanDeDobbeleer commented on src/template/random.go
> +	}
Can you add a newline here?

2024-09-19 19:28 UTC, closed without merging

2024-09-19 19:42 UTC, oliviaBahr commented
#5644